DEBUG 2015-08-17 00:26:10,844: 	 Executing command: 'status'
DEBUG 2015-08-17 00:26:10,845: 	 Found CRAB cache file /home/hep/jmonroym/.crab3
ERROR 2015-08-17 00:26:10,848: 	 Error: crab_BMM4_crabtest_Charmonium_Run2015B/ is not a valid CRAB project directory.
ERROR 2015-08-17 00:26:10,848: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 253, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/status.py", line 731, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 563, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_BMM4_crabtest_Charmonium_Run2015B/ is not a valid CRAB project directory.
DEBUG 2015-08-17 10:07:49,707: 	 Executing command: 'status'
DEBUG 2015-08-17 10:07:49,709: 	 Found CRAB cache file /home/hep/jmonroym/.crab3
ERROR 2015-08-17 10:07:49,712: 	 Error: crab_BMM4_BdToJpsiKstar_MC_13Tev/ is not a valid CRAB project directory.
ERROR 2015-08-17 10:07:49,712: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 253, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/status.py", line 731, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 563, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_BMM4_BdToJpsiKstar_MC_13Tev/ is not a valid CRAB project directory.
DEBUG 2015-08-17 15:22:59,544: 	 Executing command: 'status'
DEBUG 2015-08-17 15:22:59,545: 	 Found CRAB cache file /home/hep/jmonroym/.crab3
DEBUG 2015-08-18 09:41:14,150: 	 Executing command: 'status'
DEBUG 2015-08-18 09:41:14,151: 	 Found CRAB cache file /home/hep/jmonroym/.crab3
DEBUG 2015-08-27 12:47:42,035: 	 Executing command: 'submit'
DEBUG 2015-08-27 12:47:42,036: 	 Found CRAB cache file /home/hep/jmonroym/.crab3
DEBUG 2015-08-27 12:47:42,070: 	 Checking credentials
DEBUG 2015-08-27 12:47:42,075: 	 Found proxy file /tmp/x509up_u4338
DEBUG 2015-08-27 12:47:42,075: 	 Getting proxy life time left
DEBUG 2015-08-27 12:47:42,281: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u4338 -timeleft
 output : 549395

 error: 
 retcode : 0
DEBUG 2015-08-27 12:47:42,389: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u4338 -actimeleft
 output : 549395

 error: 
 retcode : 0
DEBUG 2015-08-27 12:47:42,389: 	 Proxy valid for 152:36:35 hours
INFO 2015-08-27 12:47:42,390: 	 Will use CRAB configuration file crabConfig_Bd2JpsiKstar.py
DEBUG 2015-08-27 12:47:42,391: 	 Loading CRAB configuration file.
DEBUG 2015-08-27 12:47:44,993: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-08-27 12:47:44,996: 	 Working area '/home/hep/jmonroym/CMSSW_7_4_6/src/Bmm/CmsswAnalysis/test/bmm4/crab_projects/crab_BMM4_BdToJpsiKstar_MC_13Tev' already exists 
Please change the requestName in the config file
ERROR 2015-08-27 12:47:44,996: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/hep/jmonroym/CMSSW_7_4_6/src/Bmm/CmsswAnalysis/test/bmm4/crab_projects/crab_BMM4_BdToJpsiKstar_MC_13Tev' already exists 
Please change the requestName in the config file
